receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319
      http:
        endpoint: 0.0.0.0:4320

processors:
  batch:
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  # ADD THIS PROCESSOR TO CONVERT OTEL ATTRIBUTES TO LOKI LABELS
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["loki.attribute.labels"], ["service.name", "job"])

exporters:
  otlp/tempo:
    endpoint: localhost:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://localhost:3100/otlp
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      # INJECT THE TRANSFORM PROCESSOR HERE
      processors: [memory_limiter, transform, batch]
      exporters: [otlphttp/loki]

  telemetry:
    metrics:
      address: 0.0.0.0:8888
