receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319
      http:
        endpoint: 0.0.0.0:4320

processors:
  batch:
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  transform:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["service.name"], "meetmind-be") where attributes["service.name"] == nil
      - context: log
        statements:
          - set(attributes["job"], body["SYSLOG_IDENTIFIER"]) where body["SYSLOG_IDENTIFIER"] != nil
          - set(attributes["loki.attribute.labels"], ["service.name", "job"])

exporters:
  otlp/tempo:
    endpoint: localhost:4317
    tls:
      insecure: true
  loki:
    endpoint: http://127.0.0.1:3100/loki/api/v1/push
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, transform, batch]
      exporters: [loki, debug]

  telemetry:
    metrics:
      address: 0.0.0.0:8888